In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
df = pd.read_csv("mnist_train_binary.csv")
y = df['label']

In [69]:
import math as mt
#for i in range(10):
#    z = x_train.iloc[i,:]
#    z = np.asarray(z)
#    w = z.reshape(28,28)
#    plt.imshow(w,cmap='gray')
#    plt.show()
count = np.zeros([2,1],dtype='int')
for i in range(len(y)):
    count[int(y.iloc[i])]=count[int(y.iloc[i])]+1
    
m = len(count)
print(m)
datas = df.as_matrix()
a = int(count[0])
b = int(count[1])
print(a,b)
xx_train = datas[0:mt.floor(int(count[0])*0.9),1:785]
yy_train = datas[0:mt.floor(int(count[0])*0.9),0]
xxx_train = datas[int(count[0]):mt.floor(int(count[1])*0.9)+int(count[0]),1:785]
yyy_train = datas[int(count[0]):mt.floor(int(count[1])*0.9)+int(count[0]),0]
#print(xx_train.shape)
#print(xxx_train.shape)
#print(yy_train.shape)
#print(yyy_train.shape)
x_train = np.vstack((xx_train,xxx_train))
y_train = np.hstack((yy_train,yyy_train))
print(y_train.shape)
print(x_train.shape)

xx_test = datas[mt.floor((a*0.9)):a,1:785]
yy_test = datas[mt.floor((a*0.9)):a,0]
xxx_test = datas[mt.floor(a+(b*0.9)):a+b,1:785]
yyy_test = datas[mt.floor(a+(b*0.9)):a+b,0]

#print(xx_test.shape)
#print(xxx_test.shape)
#print(yy_test.shape)
#print(yyy_test.shape)

x_test = np.vstack((xx_test,xxx_test))
y_test = np.hstack((yy_test,yyy_test))


2
500 500
(900,)
(900, 784)


In [70]:
for i in range(len(y_train)):
    x_train[i,:] = (x_train[i,:]-x_train[i,:].mean())/x_train[i,:].std()
print(count)

counter = np.zeros([2,1],dtype='int')
for i in range(len(y_train)):
    counter[(y_train[i])]=counter[(y_train[i])]+1
    
print(counter[0],counter[1])
mean = np.zeros([2,784],dtype='int64')
k = 0
x = 0                                           # x=0 creates nd array
for i in range(m):
    h = x+counter[i]
    for j in range(784):
        mean[k][j] =float((float(np.sum(x_train[int(x):int(h),j])))/float(counter[i]))
    x = x + counter[i]
    k = k + 1
sigma = 0
sigma = np.empty([len(y_train),784],dtype='int')
q=0
for i in range(m):
    for j in range(int(counter[i])):
        sigma[int(q)+j,:] = x_train[int(q)+j,:]-mean[i,:]
    q = q + counter[i]
#final_sigma = np.empty([10,784,784],dtype='float')
#x = 0
#temp = np.zeros([784,784],dtype='float')
#k = 0
#cnt = 0
#s = int(count[0])
#print(sigma[:,1])
#print(sigma.T[1,:])
#for i in range(len(y_train)):
#    cnt = 0
#   if(i>s-1):
#        final_sigma[int(k)]=temp
#        k=k+1
#        temp = np.zeros([784,784],dtype='float')
#        s+=int(count[int(k)])
#    temp = temp + ((np.dot((sigma[i,:]).reshape(784,1),(sigma.T[:,i]).reshape(1,784)))/(count[int(k)]))
#    final_sigma[int(k)]=temp

[[500]
 [500]]
[450] [450]


In [75]:
x = 0
final_sigma = np.zeros([784,784],dtype='float')
for i in range(m):
    h = x + counter[i]
    final_sigma += (np.dot(sigma[int(x):int(h),:].T,sigma[int(x):int(h),:]))/(counter[i]-1)
    print(final_sigma)
    x = x + counter[i]
final_sigma = final_sigma/2
print(final_sigma.shape)
updated_sigma = final_sigma

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(784, 784)


In [76]:
import math as mt
pred = np.zeros([len(y_test),1],dtype='int')
val = np.zeros([1,784],dtype='int')
vall = np.zeros([784,1],dtype='int')
for i in range(len(y_test)):
    predictor = 0
    maxi = -1
    for j in range(m):
        val = mean[j,:].reshape(1,784)
        sig_inv = np.linalg.pinv(updated_sigma)
        vall = x_test[i,:].reshape(784,1)
        dot1 = np.dot(sig_inv,vall)
        dot2 = np.dot(val,dot1)
        val_t = val.reshape(784,1)
        dot3 = np.dot(sig_inv,val_t)
        dot4 = np.dot(val,dot3)
        fa = dot2 - 0.5*(dot4) + mt.log(counter[j]/len(y_train))
        if(fa>maxi):
            maxi=fa
            predictor=j
    pred[i]=predictor


In [77]:
cnt=0
for i in range(len(y_test)):
    if(pred[i]==y_test[i]):
        cnt+=1
print(int(cnt)/len(y_test))
print(pred)

0.98
[[0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]
